language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-25.0.2

    # The SDK version used to compile your project
    - android-25

    # Support library
    - extra-android-support
    - extra-android-m2repository
    
before_install:
- chmod +x gradlew
